name: Generate and Deploy TypeDoc Documentation

on:
    push:
        branches:
            - main # Or your default branch

jobs:
    documentation:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '14'
            - run: npm install
            - run: npx typedoc --options typedoc.json
            - uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./docs
